Solved 1 task
js-tasks-ru/js-20220905_gregorykirillov pull request #1
Opened 2022-09-05 10:12 UTC by gregorykirillov

2022-09-05 10:12 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @dosandk должен запустить тесты.

2022-09-06 19:38 UTC, gregorykirillov commented
### **=== Lesson 2 ===**
- ### **1-sort-strings**
Function returns new sorted array by `.localeCompare` method and `caseFirst` parameter.

- ### **2-pick**
Function returns new object with passed keys using by `.fromEntries` and `.filter` methods.

- ### **3-omit**
Identical to the previous, but has different filter condition.

### **=== Lesson 3 ===**

- ### **1-create-getter**
Function returns arrow function which returns object value by passed path. Used optional chaining operator which returns value if property exists or undefined otherwise.

- ### **2-invert-object**
Function returns new object with swapped between keys and values using by `.fromEntries`, `.entries` and `.map` methods. 

- ### **3-trim-sybmols**
Function returns concating elements from array to string without extra symbols according passed size. Used `.reduce` method and counter.

- ### **4-uniq**
Function returns new array with unique values by tricky way in ES6 :P

2022-09-08 10:56 UTC, dosandk commented on 01-intro/1-sum/index.js
> +export const sum = (m, n) => m + n;
👍 good

2022-09-08 10:56 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +      ? a.localeCompare(b, undefined, {caseFirst: "upper"})
дубликаты кода следует устранить!

2022-09-08 10:56 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +export const pick = (obj, ...fields) => Object.fromEntries(
👍 good

2022-09-08 10:56 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  Object.entries(obj).filter(([key]) => !fields.includes(key))
👍 good

2022-09-08 10:57 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const props = path.split('.');
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2022-09-08 10:58 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  if (!size) {
старайтесь не сочетать `if...else` с тернарными выражениями

2022-09-08 10:58 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  return string.split('').reduce((acc, curr) => {
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2022-09-08 10:59 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  }, []).join('');
подумайте в чем может быть недостаток `reduce` по сравнению, например с `for...of` итерацией

2022-09-08 10:59 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +export const uniq = (arr) => [...new Set(arr)];
подумайте какие есть преимущества у `Array.from` по сравнению с спред-синтаксисом:
```
return [...new Set(arr)]
```

2022-09-08 10:59 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-09-08 11:36 UTC, gregorykirillov commented
Duplicated code was removed by adding type of sorting

2022-09-08 11:38 UTC, gregorykirillov commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const typeSort = param === 'asc' ? 1 : -1;
Duplicated code was removed by adding type of sorting

2022-09-08 11:40 UTC, gregorykirillov commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const props = path.split('.');
Recalling method was removed by using closure

2022-09-08 11:51 UTC, gregorykirillov commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  if (!obj) {return;}
Значение `undefined` возвращается напрямую путем проверки на существование переданного объекта

2022-09-08 12:08 UTC, gregorykirillov commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  }, []).join('');
Возможно, потому что `reduce` мутирует массив, в то время, как с `for...of` можно избежать этого?

2022-09-08 12:25 UTC, gregorykirillov commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +export const uniq = (arr) => [...new Set(arr)];
Думаю, спред синтаксис расширяет уже созданный пустой массив.
Array.from же создаёт новый массив и умеет работать с массивоподобными объектами

2022-09-09 21:30 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  }, []).join('');
@gregorykirillov `reduce` массив не мутирует, возвращает новое значение. Недостаток в том, что нет приемлемого способа оборвать итерацию `reduce`

2022-09-09 21:32 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +export const uniq = (arr) => [...new Set(arr)];
@gregorykirillov `Array.from` работает аналогично, но имеет в качестве бонуса второй аргумент - map-функцию, которая может быть применена к каждому элементу в процессе приведения к массиву

2022-09-09 21:32 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return arr.slice().sort((a, b) =>
`[...arr]` - более современный и короткий способ скопировать массив

2022-09-09 21:33 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    props.forEach(prop => tempObj = tempObj?.[prop]);
тут было бы неплохо "оборвать" выполнение цикла, если операция `tempObj?.[prop]` вернула `undefined`

2022-09-09 21:33 UTC, dosandk approved these changes
good 👍

2022-09-09 21:34 UTC, merged